import Appbar from "../components/modules/Appbar/Appbar";
import Footer from "../components/modules/Footer/Footer";
import "../styles/globals.scss";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="it">
      <head>
        <title>GEF - Home</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Appbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
